language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
script:
  - cd spec/dummy
  - mkdir db
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rails g brancusi:init
  - bundle exec rails g brancusi:controller home index
  - bundle exec rails g brancusi:route "@match '/', 'home#index'"
  - cd ../..
  - bundle exec rake spec

